import uuid from 'react-native-uuid';

export enum ExampleEnum {
  Zero = 0,
  One,
}

export enum Actions {
  ADD_POST_SUCCESS = 'retrospected/posts/add/success',
  DELETE_POST = 'retrospected/posts/delete',
  EDIT_POST = 'retrospected/posts/edit',
  MOVE_POST = 'retrospected/posts/move',
  LIKE_SUCCESS = 'retrospected/posts/like/success',
  ADD_POST_GROUP_SUCCESS = 'retrospected/group/add/success',
  DELETE_POST_GROUP = 'retrospected/group/delete',
  EDIT_POST_GROUP = 'retrospected/group/edit',
  RENAME_SESSION = 'retrospected/session/rename',
  JOIN_SESSION = 'retrospected/session/join',
  LEAVE_SESSION = 'retrospected/session/leave',
  EDIT_OPTIONS = 'retrospected/session/options/edit',
  EDIT_COLUMNS = 'retrospected/session/columns/edit',

  RECEIVE_POST = 'retrospected/posts/receive/add',
  RECEIVE_DELETE_POST = 'retrospected/posts/receive/delete',
  RECEIVE_EDIT_POST = 'retrospected/posts/receive/edit',
  RECEIVE_MOVE_POST = 'retrospected/posts/receive/move',
  RECEIVE_LIKE = 'retrospected/posts/receive/like',
  RECEIVE_POST_GROUP = 'retrospected/group/receive/add',
  RECEIVE_DELETE_POST_GROUP = 'retrospected/group/receive/delete',
  RECEIVE_EDIT_POST_GROUP = 'retrospected/group/receive/edit',
  RECEIVE_BOARD = 'retrospected/posts/receive-all',
  RECEIVE_OPTIONS = 'retrospected/session/options/receive',
  RECEIVE_COLUMNS = 'retrospected/session/columns/receive',
  RECEIVE_CLIENT_LIST = 'retrospected/session/receive/client-list',
  RECEIVE_SESSION_NAME = 'retrospected/session/receive/rename',
}

export const templateColumn = [
  {
    options: {
      allowActions: true,
      allowMultipleVotes: false,
      allowSelfVoting: false,
      allowAuthorVisible: false,
      maxDownVotes: null,
      maxUpVotes: null,
      allowGiphy: true,
      allowGrouping: true,
      allowReordering: true,
      blurCards: false,
      isPublic: true,
    },
    type: 'Default',
    columns: [
      {
        color: '#E8F5E9',
        icon: 'satisfied',
        label: 'What went well?',
        id: uuid.v4(),
        index: 0,
        type: 'well',
      },
      {
        color: '#FFEBEE',
        icon: 'disatisfied',
        label: 'What could be improved?',
        id: uuid.v4(),
        index: 1,
        type: 'notWell',
      },
      {
        color: '#FFFDE7',
        icon: 'sunny',
        label: 'A brilliant idea to share?',
        id: uuid.v4(),
        index: 2,
        type: 'ideas',
      },
    ],
  },
  {
    options: {
      allowActions: true,
      allowMultipleVotes: false,
      allowSelfVoting: false,
      allowAuthorVisible: false,
      maxDownVotes: null,
      maxUpVotes: null,
      allowGiphy: true,
      allowGrouping: true,
      allowReordering: true,
      blurCards: false,
      isPublic: true,
    },
    type: 'Well / Not Well',
    columns: [
      {
        color: '#E8F5E9',
        icon: 'satisfied',
        label: 'What went well?',
        id: uuid.v4(),
        index: 0,
        type: 'well',
      },
      {
        color: '#FFEBEE',
        icon: 'disatisfied',
        label: 'What could be improved?',
        id: uuid.v4(),
        index: 1,
        type: 'notWell',
      },
    ],
  },
  {
    options: {
      allowActions: true,
      allowMultipleVotes: false,
      allowSelfVoting: false,
      allowAuthorVisible: false,
      maxDownVotes: null,
      maxUpVotes: null,
      allowGiphy: true,
      allowGrouping: true,
      allowReordering: true,
      blurCards: false,
      isPublic: true,
    },
    type: 'Start / Stop / Continue',
    columns: [
      {
        color: '#E8F5E9',
        icon: 'play',
        label: 'Start',
        id: uuid.v4(),
        index: 0,
        type: 'start',
      },
      {
        color: '#FFEBEE',
        icon: 'pause',
        label: 'Stop',
        id: uuid.v4(),
        index: 1,
        type: 'stop',
      },
      {
        color: '#BBDEFB',
        icon: 'fast-forward',
        label: 'Continue',
        id: uuid.v4(),
        index: 2,
        type: 'continue',
      },
    ],
  },
  {
    options: {
      allowActions: true,
      allowMultipleVotes: false,
      allowSelfVoting: false,
      allowAuthorVisible: false,
      maxDownVotes: null,
      maxUpVotes: null,
      allowGiphy: true,
      allowGrouping: true,
      allowReordering: true,
      blurCards: false,
      isPublic: true,
    },
    type: 'Four Ls',
    columns: [
      {
        id: uuid.v4(),
        type: 'liked',
        index: 0,
        label: 'Liked',
        color: '#E8F5E9',
        icon: 'liked',
      },
      {
        id: uuid.v4(),
        type: 'learned',
        index: 1,
        label: 'Learned',
        color: '#FFEBEE',
        icon: 'disatisfied',
      },
      {
        id: uuid.v4(),
        type: 'lacked',
        index: 2,
        label: 'Lacked',
        color: '#BBDEFB',
        icon: 'help',
      },
      {
        id: uuid.v4(),
        type: 'longedFor',
        index: 3,
        label: 'Longed For',
        color: '#E1BEE7',
        icon: 'cocktail',
      },
    ],
  },
  {
    options: {
      allowActions: true,
      allowMultipleVotes: false,
      allowSelfVoting: false,
      allowAuthorVisible: false,
      maxDownVotes: null,
      maxUpVotes: null,
      allowGiphy: true,
      allowGrouping: true,
      allowReordering: true,
      blurCards: false,
      isPublic: true,
    },
    type: 'Sailboat',
    columns: [
      {
        id: uuid.v4(),
        type: 'anchor',
        index: 0,
        label: 'Anchor',
        color: '#E8F5E9',
        icon: 'link',
      },
      {
        id: uuid.v4(),
        type: 'cargo',
        index: 1,
        label: 'Boat',
        color: '#FFEBEE',
        icon: 'boat',
      },
      {
        id: uuid.v4(),
        type: 'island',
        index: 2,
        label: 'Island',
        color: '#BBDEFB',
        icon: 'cocktail',
      },
      {
        id: uuid.v4(),
        type: 'wind',
        index: 3,
        label: 'Wind',
        color: '#E1BEE7',
        icon: 'gesture',
      },
      {
        id: uuid.v4(),
        type: 'rock',
        index: 4,
        label: 'Rock',
        color: '#FFE0B2',
        icon: 'fitness',
      },
    ],
  },
];
